# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

charSepXPtr <- function(path, n, m, r) {
    .Call(`_mmapcharr_charSepXPtr`, path, n, m, r)
}

decodeMat <- function(source, code) {
    .Call(`_mmapcharr_decodeMat`, source, code)
}

decodeVec <- function(source, code) {
    .Call(`_mmapcharr_decodeVec`, source, code)
}

extractVec <- function(obj, elemInd) {
    .Call(`_mmapcharr_extractVec`, obj, elemInd)
}

extractMat <- function(obj, rowInd, colInd) {
    .Call(`_mmapcharr_extractMat`, obj, rowInd, colInd)
}

nline_cpp <- function(obj) {
    .Call(`_mmapcharr_nline_cpp`, obj)
}

